version: '3'
services:
  php:
    build:
      context: ./.docker/php/
      dockerfile: Dockerfile
    volumes:
     - ./:/var/www
     - ./docker/php/local.ini:/usr/local/etc/php/conf.d/php.ini

  nginx:
    build:
      context: ./.docker/nginx/
      dockerfile: Dockerfile
    ports:
      - 3380:80
    volumes:
     - ./:/var/www

  database:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: esgi
      POSTGRES_USER: esgi
      POSTGRES_PASSWORD: Test1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

  #maildev:
  #  image: maildev/maildev
  #  ports:
  #    - 1080:1080
  #    - 1025:1025

volumes:
  pgdata:
